name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
          MONGO_INITDB_DATABASE: nsl

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push

      - name: Run MongoDB container
        run: |
          docker-compose -f docker-compose.yml up -d mongodb
          
      - name: Run server and client containers
        run: |
          docker-compose -f docker-compose.yml up -d server client nginx

      - name: Run tests
        run: docker-compose -f docker-compose.yml exec server npm test

      - name: Teardown
        run: docker-compose -f docker-compose.yml down
