name: CI/CD Pipeline

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 27017:27017

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      run: |
        docker-compose -f docker-compose.yaml build
        docker-compose -f docker-compose.yaml push

    - name: Deploy to Vercel
      env:
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: |
        npm install -g vercel
        vercel --prod --token $VERCEL_TOKEN --project $VERCEL_PROJECT_ID --cwd .

    - name: Deploy to Render.com
      run: |
        curl -X POST 'https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys' \
        -H 'Accept: application/json' \
        -H 'Authorization: Bearer ${{ secrets.RENDER_API_KEY }}' \
        -d ''
